# Default values for tarantool.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ClusterEnv: dev
ClusterName: examples-kv-cluster

namespace: tarantool

image:
  repository: tarantool/tarantool-operator-examples-kv
  tag: 0.0.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

Prometheus:
  port: 8081
  path: /metrics

RoleConfig:
  - RoleName: routers
    ReplicaCount: 1
    ReplicaSetCount: 1
    DiskSize: 1Gi
    CPUallocation: 0.25
    MemtxMemoryMB: 256
    RolesToAssign: router

  - RoleName: storage
    ReplicaCount: 2
    ReplicaSetCount: 1
    DiskSize: 1Gi
    CPUallocation: 0.25
    MemtxMemoryMB: 256
    RolesToAssign: storage
