name: Synchronization
on: [push]
jobs:
  synchronization:
    runs-on: ["ubuntu"]
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PUSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace
      - name: Fetch unshallow
        run: git fetch --unshallow old
      - name: Set remote url
        run: git remote set-url --push origin git@git.picodata.io:picodata/picodata/tarantool-module.git
      - name: Push files
        run: git push
